services:
  - type: web
    name: pdf-shelf-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pdf-shelf-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RUST_LOG
        value: info
      # AWS/S3 Configuration - These must be set manually in Render Dashboard
      # Go to Service Settings > Environment and add these variables:
      - key: AWS_ACCESS_KEY_ID
        value: SET_IN_DASHBOARD # Set this value manually in Render Dashboard
      - key: AWS_SECRET_ACCESS_KEY
        value: SET_IN_DASHBOARD # Set this value manually in Render Dashboard
      - key: AWS_REGION
        value: us-east-1
      - key: AWS_S3_BUCKET
        value: SET_IN_DASHBOARD # Set this value manually in Render Dashboard
      - key: AWS_ENDPOINT_URL
        value: https://s3.amazonaws.com
      # MinIO-compatible variables (for backward compatibility with Rust code)
      # These point to the same AWS credentials but use MinIO variable names
      - key: MINIO_ENDPOINT
        value: https://s3.amazonaws.com
      - key: MINIO_ACCESS_KEY
        value: SET_IN_DASHBOARD # This should match AWS_ACCESS_KEY_ID - set manually
      - key: MINIO_SECRET_KEY
        value: SET_IN_DASHBOARD # This should match AWS_SECRET_ACCESS_KEY - set manually
      - key: MINIO_BUCKET
        value: SET_IN_DASHBOARD # This should match AWS_S3_BUCKET - set manually
      # MTN MoMo Configuration
      - key: MTN_URL
        value: https://sandbox.momodeveloper.mtn.com
      - key: MTN_COLLECTION_PRIMARY_KEY
        value: SET_IN_DASHBOARD # Set this value manually in Render Dashboard
      - key: MTN_COLLECTION_SECONDARY_KEY
        value: SET_IN_DASHBOARD # Set this value manually in Render Dashboard
      - key: MTN_CALLBACK_URL
        value: SET_IN_DASHBOARD_CALLBACK_URL # Set this in Render Dashboard. Use ${RENDER_EXTERNAL_URL}/api/payments/callback (where RENDER_EXTERNAL_URL is for this 'pdf-shelf-api' service)
      # - fromService: # 'url' property is not directly available, RENDER_EXTERNAL_URL is preferred
      #     type: web
      #     name: pdf-shelf-api
      #     property: host # Use host and construct, or rely on RENDER_EXTERNAL_URL
      - key: MTN_CURRENCY
        value: EU

  - type: web
    name: pdf-shelf-frontend
    runtime: static
    buildCommand: npm ci && npm run build
    pullRequestPreviewsEnabled: true
    branch: main
    rootDir: ./frontend
    staticPublishPath: dist # Changed: Correct property name for publish directory
    envVars:
      - key: VITE_API_URL
        value: ${pdf-shelf-api.RENDER_EXTERNAL_URL} # Dynamically uses the backend URL
      # - fromService:
      #     type: web
      #     name: pdf-shelf-api
      #     property: host # 'url' property is not directly available
      - key: REACT_APP_API_URL
        value: ${pdf-shelf-api.RENDER_EXTERNAL_URL} # Dynamically uses the backend URL
      # - fromService:
      #     type: web
      #     name: pdf-shelf-api
      #     property: host # 'url' property is not directly available

databases:
  - name: pdf-shelf-db
    plan: free
    databaseName: pdfshelf
    user: pdfshelf
    region: oregon